### ISSUE TITLE
切换成url 模式 模式报错

### ISSUE THREAD

**Issue by he5050** [javaLuo/react-luo#31]
您好，今天刚刚拉下您的项目，在开发模下从hashURL切换到url，强制刷新页面会报错
内容如下
``` javascript
Error: invalid argument
    at pathToArray (E:\github\react-luo\node_modules\memory-fs\lib\MemoryFileSystem.js:44:10)
    at MemoryFileSystem.readFileSync (E:\github\react-luo\node_modules\memory-fs\lib\MemoryFileSystem.js:103:13)
    at MemoryFileSystem.(anonymous function) [as readFile] (E:\github\react-luo\node_modules\memory-fs\lib\MemoryFileSystem.js:300:34)
    at app.get (E:\github\react-luo\server.js:47:31)
    at Layer.handle [as handle_request] (E:\github\react-luo\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\github\react-luo\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\github\react-luo\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\github\react-luo\node_modules\express\lib\router\layer.js:95:5)
    at E:\github\react-luo\node_modules\express\lib\router\index.js:281:22
    at param (E:\github\react-luo\node_modules\express\lib\router\index.js:354:14)
```

**Comment by he5050** [comment]
可能output的路径引起的 在output的path相对路径引起的

**Comment by javaLuo** [comment]
好的，我看看

**Comment by javaLuo** [comment]
嗯，确实有问题，应该用绝对路径。
但在MAC上是好的..

**Comment by he5050** [comment]
好的 那我关了这个issues了
